### ISSUE TITLE
Geoexplorer build fails

### ISSUE THREAD

**Issue by EASC** [boundlessgeo/suite#1002]
Hello, I'm a new Linux User. I'm trying to build geoexplorer.war in Ubuntu 14.04 following next steps:
Install java-jdk 1.8.0_73, Maven 3.2.5, Ant 1.9.3, and Ivy 2.4
next I follow https://github.com/boundlessgeo/suite/tree/master/geoexplorer, however when I run 
ant build
The following error message comes up:
[ivy:report] Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[ivy:report] Advertencias del compilador:
[ivy:report]   WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
[ivy:report] Processing /home/andres/.ivy2/cache/com.boundlessgeo.suite-geoexplorer-compile.xml to /home/andres/suite/geoexplorer/target/ivy-report/com.boundlessgeo.suite-geoexplorer-compile.html
[ivy:report] Warning:  org.apache.xerces.parsers.SAXParser: Feature 'http://javax.xml.XMLConstants/feature/secure-processing' is not recognized.
[ivy:report] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
[ivy:report] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[ivy:report] Warning:  org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[ivy:report] Advertencias del compilador:
[ivy:report]   WARNING:  'org.apache.xerces.jaxp.SAXParserImpl: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.'
[ivy:report] Processing /home/andres/.ivy2/cache/com.boundlessgeo.suite-geoexplorer-compile.xml to /home/andres/suite/geoexplorer/target/ivy-report/com.boundlessgeo.suite-geoexplorer-compile.graphml
[ivy:report] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://javax.xml.XMLConstants/property/accessExternalDTD' is not recognized.
[ivy:report] Warning:  org.apache.xerces.parsers.SAXParser: Property 'http://www.oracle.com/xml/jaxp/properties/entityExpansionLimit' is not recognized.
[ivy:retrieve] :: retrieving :: com.boundlessgeo.suite#geoexplorer
[ivy:retrieve] 	confs: [compile]
[ivy:retrieve] 	10 artifacts copied, 0 already retrieved (3718kB/127ms)
     [copy] Copying 77 files to /home/andres/suite/geoexplorer/target/war/WEB-INF/app
     [copy] Copying 23 files to /home/andres/suite/geoexplorer/target/war/WEB-INF/app/stick
     [copy] Copying 332 files to /home/andres/suite/geoexplorer/target/war/WEB-INF/app/static/externals/ext
     [copy] Copying 38 files to /home/andres/suite/geoexplorer/target/war/WEB-INF/app/static/externals/openlayers/theme
     [copy] Copying 12 files to /home/andres/suite/geoexplorer/target/war/WEB-INF/app/static/externals/geoext/resources
     [copy] Copying 98 files to /home/andres/suite/geoexplorer/target/war/WEB-INF/app/static/externals/gxp/src/theme
     [copy] Copying 4 files to /home/andres/suite/geoexplorer/target/war/WEB-INF/app/static/externals/printpreview/resources
    [mkdir] Created dir: /home/andres/suite/geoexplorer/target/war/WEB-INF/app/static/script
     [java] Exception in thread "main" java.lang.NoClassDefFoundError: org/mozilla/javascript/WrapFactory
     [java] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [java] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
     [java] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [java] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
     [java] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
     [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
     [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java] 	at java.lang.ClassLoader.defineClass1(Native Method)
     [java] 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
     [java] 	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
     [java] 	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
     [java] 	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
     [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
     [java] 	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
     [java] 	at java.security.AccessController.doPrivileged(Native Method)
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java] 	at java.lang.Class.getDeclaredConstructors0(Native Method)
     [java] 	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
     [java] 	at java.lang.Class.getConstructor0(Class.java:3075)
     [java] 	at java.lang.Class.newInstance(Class.java:412)
     [java] 	at org.ringojs.tools.launcher.Main.<init>(Main.java:54)
     [java] 	at org.ringojs.tools.launcher.Main.main(Main.java:44)
     [java] Caused by: java.lang.ClassNotFoundException: org.mozilla.javascript.WrapFactory
     [java] 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
     [java] 	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
     [java] 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
     [java] 	... 30 more

BUILD FAILED
/home/andres/suite/geoexplorer/build.xml:78: Java returned: 1

Could somebody please help me with this inconvenience?
Thanks!

**Comment by siavash1986** [comment]
Hi there

I have the same issue when I tried to build Geoexplorer on my Ubuntu 15.04, I did however try some other environments but same exception was thrown every time I ran build.
ant solution to this problem yet?

**Comment by EASC** [comment]
Hi siavash1986,
I have not found a solution for this problem. I tried with different ant, jdk and mvn versions but the result is always the same :(
So I installed the complete suite from this page http://suite.opengeo.org/docs/latest/intro/installation/ubuntu/install.html#intro-installation-ubuntu-install while I find a solution for this issue.
