### ISSUE TITLE
Unable crop coverage witch is result of gs:BarnersSurface   with WPS chain in sld

### ISSUE THREAD

**Issue by kangming** [boundlessgeo/suite#994]
it's throw below error:
      29 十二月 18:48:43 ERROR [geotools.jdbc] - Failed to execute statement SELECT "gid","id","stationcode","stationname","station_lo","station_la","citycode","cityname","provincena","remarks","weather_st","weather__1","weather__2","weather__3","weather__4","distance","area","id_d1","id_d2","id_d3","地域",encode(ST_AsEWKB("geom"),'base64') as "geom","code","o3_8h" FROM (select s.*,p.o3_8h from station s left join t_sc_pollutant_v0020_hour p on p.stationcode=s.code  where p.monitordate= to_timestamp('2015-10-19 16:00:00','YYYY-MM-DD HH24:MI:SS')
) as "vtable" WHERE  "geom" && ST_GeomFromText('POLYGON ((-∞ -∞, -∞ ∞, ∞ ∞, ∞ -∞, -∞ -∞))', 3857)
29 十二月 18:48:43 DEBUG [geotools.jdbc] - CLOSE CONNECTION
29 十二月 18:48:43 DEBUG [geotools.jdbc] - CLOSE CONNECTION
29 十二月 18:48:43 ERROR [geoserver.ows] - 
org.geoserver.platform.ServiceException: Error rendering coverage on the fast path
	at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:344)
	at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:259)
	at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:132)
	at org.geoserver.wms.GetMap.executeInternal(GetMap.java:504)
	at org.geoserver.wms.GetMap.run(GetMap.java:248)
	at org.geoserver.wms.GetMap.run(GetMap.java:119)
	at org.geoserver.wms.DefaultWebMapService.getMap(DefaultWebMapService.java:320)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:319)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:183)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:150)
	at org.geoserver.kml.WebMapServiceKmlInterceptor.invoke(WebMapServiceKmlInterceptor.java:34)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:62)
	at org.geoserver.gwc.wms.CacheSeedingWebMapService.invoke(CacheSeedingWebMapService.java:36)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:80)
	at org.geoserver.gwc.wms.CachingWebMapService.invoke(CachingWebMapService.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.geoserver.ows.util.RequestObjectLogger.invoke(RequestObjectLogger.java:55)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:172)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:202)
	at com.sun.proxy.$Proxy66.getMap(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.geoserver.ows.Dispatcher.execute(Dispatcher.java:845)
	at org.geoserver.ows.Dispatcher.handleRequestInternal(Dispatcher.java:275)
	at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:153)
	at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:48)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:923)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:852)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:882)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:778)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:654)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1320)
	at org.geoserver.filters.ThreadLocalsCleanupFilter.doFilter(ThreadLocalsCleanupFilter.java:28)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:75)
	at org.geoserver.wms.animate.AnimatorFilter.doFilter(AnimatorFilter.java:71)
	at org.geoserver.filters.SpringDelegatingFilter$Chain.doFilter(SpringDelegatingFilter.java:71)
	at org.geoserver.filters.SpringDelegatingFilter.doFilter(SpringDelegatingFilter.java:46)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.geoserver.platform.AdvancedDispatchFilter.doFilter(AdvancedDispatchFilter.java:50)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:311)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:116)
	at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:83)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:113)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerAnonymousAuthenticationFilter.doFilter(GeoServerAnonymousAuthenticationFilter.java:54)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.authentication.www.BasicAuthenticationFilter.doFilter(BasicAuthenticationFilter.java:150)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.geoserver.security.filter.GeoServerBasicAuthenticationFilter.doFilter(GeoServerBasicAuthenticationFilter.java:83)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:69)
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:87)
	at org.geoserver.security.filter.GeoServerSecurityContextPersistenceFilter$1.doFilter(GeoServerSecurityContextPersistenceFilter.java:53)
	at org.geoserver.security.filter.GeoServerCompositeFilter$NestedFilterChain.doFilter(GeoServerCompositeFilter.java:73)
	at org.geoserver.security.filter.GeoServerCompositeFilter.doFilter(GeoServerCompositeFilter.java:92)
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:323)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:173)
	at org.geoserver.security.GeoServerSecurityFilterChainProxy.doFilter(GeoServerSecurityFilterChainProxy.java:135)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:346)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:259)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.geoserver.filters.LoggingFilter.doFilter(LoggingFilter.java:83)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.geoserver.filters.GZIPFilter.doFilter(GZIPFilter.java:42)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.geoserver.filters.SessionDebugFilter.doFilter(SessionDebugFilter.java:48)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.geoserver.filters.FlushSafeFilter.doFilter(FlushSafeFilter.java:44)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:76)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1291)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:443)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:532)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1044)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:372)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:189)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:978)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:369)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:486)
	at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:933)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:995)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.geoserver.platform.ServiceException: java.lang.RuntimeException: Failed to evaluate the process function, error is: java.lang.RuntimeException: java.io.IOException
	at org.geoserver.wms.map.RenderedImageMapOutputFormat.directRasterRender(RenderedImageMapOutputFormat.java:1055)
	at org.geoserver.wms.map.RenderedImageMapOutputFormat.produceMap(RenderedImageMapOutputFormat.java:342)
	... 116 more
Caused by: java.lang.RuntimeException: Failed to evaluate the process function, error is: java.lang.RuntimeException: java.io.IOException
	at org.geotools.process.function.ProcessFunction.evaluate(ProcessFunction.java:155)
	at org.geotools.process.function.ParameterFunction.evaluate(ParameterFunction.java:104)
	at org.geotools.process.function.ParameterFunction.evaluate(ParameterFunction.java:120)
	at org.geotools.process.function.ProcessFunction.evaluateInputs(ProcessFunction.java:174)
	at org.geotools.process.function.ProcessFunction.evaluate(ProcessFunction.java:137)
	at org.geotools.renderer.lite.RenderingTransformationHelper.applyRenderingTransformation(RenderingTransformationHelper.java:216)
	at org.geoserver.wms.map.RenderedImageMapOutputFormat.directRasterRender(RenderedImageMapOutputFormat.java:1008)
	... 117 more
Caused by: org.geotools.process.ProcessException: java.lang.RuntimeException: java.io.IOException
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:565)
	at org.geotools.process.function.ProcessFunction.evaluate(ProcessFunction.java:142)
	... 123 more
Caused by: java.lang.RuntimeException: java.io.IOException
	at org.geotools.data.store.ContentFeatureCollection.features(ContentFeatureCollection.java:176)
	at org.geotools.process.vector.BarnesSurfaceProcess.extractPoints(BarnesSurfaceProcess.java:388)
	at org.geotools.process.vector.BarnesSurfaceProcess.execute(BarnesSurfaceProcess.java:226)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.geotools.process.factory.AnnotationDrivenProcessFactory$InvokeMethodProcess.execute(AnnotationDrivenProcessFactory.java:549)
	... 124 more
Caused by: java.io.IOException
	at org.geotools.jdbc.JDBCFeatureSource.getReaderInternal(JDBCFeatureSource.java:649)
	at org.geotools.data.store.ContentFeatureSource.getReader(ContentFeatureSource.java:634)
	at org.geotools.data.store.ContentFeatureCollection.features(ContentFeatureCollection.java:173)
	... 131 more
Caused by: java.sql.SQLException: org.postgresql.util.PSQLException: ERROR: parse error - invalid geometry
  建议："POLYGON ((-?" <-- parse error at position 12 within geometry
	at org.geotools.jdbc.JDBCFeatureReader.<init>(JDBCFeatureReader.java:155)
	at org.geotools.jdbc.JDBCFeatureSource.getReaderInternal(JDBCFeatureSource.java:619)
	... 133 more
Caused by: org.postgresql.util.PSQLException: ERROR: parse error - invalid geometry
  建议："POLYGON ((-?" <-- parse error at position 12 within geometry
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2270)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1998)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:255)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:570)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:406)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeQuery(AbstractJdbc2Statement.java:286)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.apache.commons.dbcp.DelegatingStatement.executeQuery(DelegatingStatement.java:208)
	at org.geotools.jdbc.JDBCFeatureReader.<init>(JDBCFeatureReader.java:146)
	... 134 more

**Comment by kangming** [comment]
mys sld :
     <?xml version="1.0" encoding="ISO-8859-1"?>
<StyledLayerDescriptor version="1.0.0"
     xsi:schemaLocation="http://www.opengis.net/sld StyledLayerDescriptor.xsd"
     xmlns="http://www.opengis.net/sld"
     xmlns:ogc="http://www.opengis.net/ogc"
     xmlns:xlink="http://www.w3.org/1999/xlink"
     xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <NamedLayer>
    <Name>CropCoverage</Name>
    <UserStyle>
      <Title>Crop Coverage</Title>
      <Abstract>Extracts contours from a computed surface</Abstract>
      <FeatureTypeStyle>
        <Transformation>
          <ogc:Function name="gs:CropCoverage">
            <ogc:Function name="parameter">
              <ogc:Literal>coverage</ogc:Literal>

              <ogc:Function name="gs:BarnesSurface">
                <ogc:Function name="parameter">
                  <ogc:Literal>data</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>valueAttr</ogc:Literal>
                  <ogc:Literal>o3_8h</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>scale</ogc:Literal>
                  <ogc:Literal>300000</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>convergence</ogc:Literal>
                  <ogc:Literal>0.2</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>passes</ogc:Literal>
                  <ogc:Literal>3</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>minObservations</ogc:Literal>
                  <ogc:Literal>1</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>maxObservationDistance</ogc:Literal>
                  <ogc:Literal>300000</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>pixelsPerCell</ogc:Literal>
                  <ogc:Literal>10</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>queryBuffer</ogc:Literal>
                  <ogc:Literal>1100000</ogc:Literal>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>outputBBOX</ogc:Literal>
                  <ogc:Function name="env">
                    <ogc:Literal>wms_bbox</ogc:Literal>
                  </ogc:Function>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>outputWidth</ogc:Literal>
                  <ogc:Function name="env">
                    <ogc:Literal>wms_width</ogc:Literal>
                  </ogc:Function>
                </ogc:Function>

                <ogc:Function name="parameter">
                  <ogc:Literal>outputHeight</ogc:Literal>
                  <ogc:Function name="env">
                    <ogc:Literal>wms_height</ogc:Literal>
                  </ogc:Function>
                </ogc:Function>

              </ogc:Function>
            </ogc:Function>

            <ogc:Function name="parameter">
              <ogc:Literal>cropShape</ogc:Literal>
              <ogc:Function name="env">
                <ogc:Literal>shape</ogc:Literal>
                <ogc:Literal>
                  POLYGON((12679220.5449551 4733685.69206447,12898591.968062 4713152.82010571,13058134.8212306 4439899.46114607,13030214.821926 4052340.79528089,12735060.5435642 4028261.06778929,12483780.5498236 4076471.69742768,12180649.1288033 4330580.49744829,12264409.1267168 4525151.37667656,12264409.1267168 4525151.37667656,12364123.4099472 4728548.57087371,12364123.4099472 4728548.57087371,12679220.5449551 4733685.69206447))
                </ogc:Literal>
              </ogc:Function>
            </ogc:Function>

            <ogc:Function name="parameter">
              <ogc:Literal>simplify</ogc:Literal>
              <ogc:Literal>true</ogc:Literal>
            </ogc:Function>

          </ogc:Function>
        </Transformation>

        <Rule>
          <Name>rule1</Name>
          <RasterSymbolizer>

            <Geometry>
              <ogc:PropertyName>geom</ogc:PropertyName>
            </Geometry>

            <Opacity>1</Opacity>

            <ColorMap type="ramp">

            <ColorMapEntry color="#4f0067" quantity="-999" label="nodata" opacity="0"/>

            <ColorMapEntry color="#990099" quantity="30" label="values"/>

            <ColorMapEntry color="#e600e6" quantity="50" label="values" />

            <ColorMapEntry color="#9e00ff" quantity="75" label="values" />

            <ColorMapEntry color="#6600ff" quantity="100" label="values" />
            <ColorMapEntry color="#0000ff" quantity="120" label="values" />

            <ColorMapEntry color="#004aff" quantity="140" label="values" />

            <ColorMapEntry color="#0073ff" quantity="160" label="values" />

            <ColorMapEntry color="#00a3ff" quantity="200" label="values" />

            <ColorMapEntry color="#00ccff" quantity="250" label="values" />

            <ColorMapEntry color="#00e6ff" quantity="270" label="values" />

            <ColorMapEntry color="#00ffff" quantity="300" label="values" />

            <ColorMapEntry color="#00ffb3" quantity="330" label="values" />

            <ColorMapEntry color="#84fe00" quantity="350" label="values" />

            <ColorMapEntry color="#ceff00" quantity="370" label="values" />

            <ColorMapEntry color="#ffff00" quantity="390" label="values" />

            <ColorMapEntry color="#fde006" quantity="410" label="values" />

            <ColorMapEntry color="#ffc608" quantity="420" label="values" />

            <ColorMapEntry color="#ffaf00" quantity="440" label="values" />

            <ColorMapEntry color="#fc9802" quantity="450" label="values" />

            <ColorMapEntry color="#fe7600" quantity="480" label="values" />

            <ColorMapEntry color="#ff5100" quantity="490" label="values" />

            <ColorMapEntry color="#f8b6bf" quantity="500" label="values" />

           </ColorMap>
         </RasterSymbolizer>
       </Rule>
      </FeatureTypeStyle>
    </UserStyle>
  </NamedLayer>
</StyledLayerDescriptor>

**Comment by DBlasby** [comment]
Looks like the problem is the SQL it is creating;
ST_GeomFromText('POLYGON ((-∞ -∞, -∞ ∞, ∞ ∞, ∞ -∞, -∞ -∞))', 3857)

**Comment by kangming** [comment]
ST_GeomFromText('POLYGON ((-∞ -∞, -∞ ∞, ∞ ∞, ∞ -∞, -∞ -∞))', 3857)    
Looks like not get layer's bbox.
