### ISSUE TITLE
Connection to GeoServer fails if it contains a (WMS) store with whitespace in name

### ISSUE THREAD

**Issue by torse** [boundlessgeo/suite#995]
(Version 0.1.1 / GS 2.8.1) Resulting in following error in QGIS console:
```
Tried to make a GET request to http://localhost:8080/rest/workspaces/ws1/wmsstores/My WMS Store/wmslayers.xml but got a 505 status code: 
Traceback (most recent call last):
  File "/home/user/.qgis2/python/plugins/geoserverexplorer/gui/explorer.py", line 98, in run
    command(*params)
  File "/home/user/.qgis2/python/plugins/geoserverexplorer/gui/gsexploreritems.py", line 534, in populate
    raise e
FailedRequestError: Tried to make a GET request to http://localhost:8080/rest/workspaces/ws1/wmsstores/My WMS Store/wmslayers.xml
```

**Comment by stefan-gisworks** [comment]
Same Problem here. GS 2.8.0 Version 0.1.1
